// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckExportOutput(arg1:string):Promise<main.ExportOutputCheck>;
export function CreateZipArchive(arg1:main.ZipRequest):Promise<main.ZipResult>;
export function GetConfig():Promise<main.AppConfig>;
export function GetGeneratedFiles():Promise<Array<main.GeneratedFile>>;

export function StartTask(arg1:string,arg2:main.ExportRequest):Promise<void>;
