// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckExportOutput(arg1) {
  return window['go']['main']['App']['CheckExportOutput'](arg1);
}

export function ClearGeneratedFiles() {
  return window['go']['main']['App']['ClearGeneratedFiles']();
}

export function CreateZipArchive(arg1) {
  return window['go']['main']['App']['CreateZipArchive'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetGeneratedFiles() {
  return window['go']['main']['App']['GetGeneratedFiles']();
}

export function PreviewExport(arg1) {
  return window['go']['main']['App']['PreviewExport'](arg1);
}

export function StartTask(arg1, arg2) {
  return window['go']['main']['App']['StartTask'](arg1, arg2);
}
