// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appcore} from '../models';

export function CheckExportOutput(arg1:string):Promise<appcore.ExportOutputCheck>;

export function ClearGeneratedFiles():Promise<void>;

export function CreateZipArchive(arg1:appcore.ZipRequest):Promise<appcore.ZipResult>;

export function GetConfig():Promise<appcore.AppConfig>;

export function GetGeneratedFiles():Promise<Array<appcore.GeneratedFile>>;

export function PreviewExport(arg1:appcore.ExportRequest):Promise<appcore.ExportPreview>;

export function StartTask(arg1:string,arg2:appcore.ExportRequest):Promise<void>;
